INSERT INTO CLIENTE (NOME, SEXO, ENDEREÇO, TELEFONE, CPF) VALUES ('CLARA', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '883665843',22222222222);

/*O COMANDO SELECT */
/*SELEÇÃO, PROJEÇÃO E JUNÇÃO*/

SELECT NOW ();

SELECT NOW() AS DATA_HORA, 'FELIPE MAFRA' AS PROFESSOR;

SELECT 'FELIPE MAFRA';

SELECT 'BANCO DE DADOS';

/*ALIAS DE COLUNAS*/

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

/*PROJETANDO A COLUNA  (UTILIZANDO AS PARA TROCAR O 'NOME' POR 'CLIENTE'*/
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

/*COM O COMANDO ABAIXO É POSSÍVEL ALTERAR A ORDEM DE PROJEÇÃO DE COLUNAS. BASTA TROCAR AS POSIÇÕES*/
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

/*SELECT É USADO PARA 'PROJEÇÃO' DE TABELAS*/
SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/*USAR APENAS PARA FINS DE ESTUDO! NUNCA UTILIZAR NO TRABALHO*/
SELECT * FROM CLIENTE;
