/*Profissional de tunning*/

/*TIPAGEM DE TABELAS DE BANCOS DE DADOS*/

/*
PARA TEXTOS CURTOS(PALAVRAS) UTILIZAMOS CHAR E VARCHAR
PARA NÚMEROS INTEIROS E REAIS UTILIZAMOS FLOAT E INT
PARA DOCUMENTOS UTILIZAMOS O BLOB
PARA TEXTOS GRANDES UTILIZAMOS O TEXT


CHAR (10)
[ | | | | | | | | | ]

VARCHAR(10)
[ | | | | | | | | | ]

1 CARACTER = 1 BYTE

O VARCHAR É VARIÁVEL, MAS O CHAR TEM TAMANHO FIXO.

CHAR (10)
[ J|O |Ã |O | | | | | | ] = 10 BYTES

VARCHAR (10) 
[ J|O |Ã |O ] = 4 BYTES

O VARCHAR VARIOU PARA 4 CARACTERES

QUANDO UTILIZAR O CHAR?

UTILIZAR CHAR QUANDO:
O NÚMERO DE CARACTERES DA COLUNA NUNCA FOR VARIANTE.
POR EXEMPLO: UNIDADE FEDERATIVA: BA -> SEMPRE DOIS DÍGITOS
CPF: 00000000000 -> SEMPRE ONZE DÍGITOS

*/