/*ENUM -> ENUMERAÇÃO
É UM CONJUNTO DE DADOS ENUMERADOS (FIXO)

TIPOS NUMÉRICOS 

INT (NÚMEROS INTEIROS) ---- FLOAT (NÚMEROS REAIS)

NÚMEROS DO TIPO FLOAT -> FLOAT(TOTAL, VÍRGULA)

FLOAT(10,2) -> DEZ CASAS DECIMAIS ONDE DUAS APÓS A VÍRGULA

NÚMEROS DO TIPO INTEIRO TEM UM LIMITE DE 11 DÍGITOS.
SE NÃO FOR FEITO NENHUM CÁLCULO UTILIZANDO ESSES NÚMEROS, NÃO CONVÉM USAR O INT, MAS SIM O VARCHAR.
*/