/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'LILIAN@HOTMAIL.COM'; -- DESSA FORMA TODOS OS CAMPOS DE EMAIL FORAM ALTERADOS PARA 'LILIAN@HOTMAIL.COM'

SELECT NOME, EMAIL FROM CLIENTE;

/*
WHERE VAI SER O SEU MELHOR AMIGO DA VIDA, PARA A VIDA INTEIRA
*/

SELECT * FROM CLIENTE WHERE NOME = 'JOAO';

UPDATE CLIENTE SET EMAIL = 'JOAO@IG.COM.BR' WHERE NOME = 'JOAO';

SELECT NOME, EMAIL FROM CLIENTE;

UPDATE CLIENTE SET EMAIL = 'JORGE@IG.COM.BR' WHERE NOME = 'JORGE';

UPDATE CLIENTE SET EMAIL = 'CELIA@HOTMAIL.COM' WHERE NOME = 'CELIA';

UPDATE CLIENTE SET EMAIL = 'ANA@GMAIL.COM' WHERE NOME = 'ANA';

UPDATE CLIENTE SET EMAIL = 'CARLA@BOL.COM.BR' WHERE NOME = 'CARLA';